language: android
jdk: oraclejdk7
cache: false
sudo: false
env:
  matrix:
  - ANDROID_TARGET=android-10 ANDROID_ABI=armeabi
  - ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
  - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
  global: MALLOC_ARENA_MAX=2
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - extra-android-support
    - extra-android-m2repository
    - android-22
    - android-23
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-23
before_install:
  - export TERM=dumb
before_script:
- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
- emulator -avd test -no-skin -no-audio -no-window &
- adb wait-for-device
- adb shell input keyevent 82 &
script: "./gradlew connectedCheck"
notifications:
  slack:
    secure: Ov7XJdmH5SB1zQlVVT7gozs42Ju1XIONyC2B8+dwKqAxdXEjscTUFkKOPOLVGtfloAd2/8t70LeB1CxIByBMy/WMU4VNYloGMD2FrwFasGhveXCVubKla33miE/Iq+4/R3TXxWffk4Pvvj6BE3D0rQJw8+0RvbBzLsh928USj7E=
